version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: bitriseio/android-ndk:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - run: ./gradlew androidDependencies
      - run: ./gradlew clean assembleRelease
      - store_artifacts:
          path: PdCore/build/outputs/aar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
