version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: docker pull bitriseio/android-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build AAR
          command: ./gradlew clean assembleRelease
      - store_artifacts:
          path: PdCore/build/outputs/aar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
