.PHONY: all

all:
	ndk-build
	cp libs/armeabi-v7a/libexpr.so libs/armeabi-v7a/libexpr_tilde.so
	cp libs/armeabi-v7a/libexpr.so libs/armeabi-v7a/libfexpr_tilde.so
	cp libs/armeabi/libexpr.so libs/armeabi/libexpr_tilde.so
	cp libs/armeabi/libexpr.so libs/armeabi/libfexpr_tilde.so
	cp libs/x86/libexpr.so libs/x86/libexpr_tilde.so
	cp libs/x86/libexpr.so libs/x86/libfexpr_tilde.so

